chore: update anything

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,14 +4,15 @@ error="$(tput setaf 1)✖️$(tput sgr0)"
 echo
 echo "$(tput bold)# PRE-COMMIT SCRIPT$(tput sgr0)"
 
-# Check files to commit
-echo "> Check staged files to commit"
+# Check staged changes to commit
+echo "> Check staged changes to commit"
 staged=$(git diff --name-only --cached)
 if [[ -z $staged ]]; then
-	echo "$error Nothing to commit."
-	echo
-    exit 1
+    echo "$error Nothing to commit."
+    echo
+    exit 0
 fi
+echo "$passed Staged changes were found."
 echo
 
 # Check unstaged changes
@@ -19,11 +20,26 @@ echo "> Check unstaged changes from staged files"
 changes=$(git status --short | grep "^MM" || echo "")
 if [[ -n $changes ]]; then
     echo "$(tput setaf 1)$changes$(tput sgr0)"
-	echo
+    echo
     exit 1
 fi
 echo "$passed No unstaged changes."
 echo
+
+# Check files extension
+ext_list="\.(js|cjs|mjs|jsx|ts|cts|mts|tsx|json|jsonc|json5|css|scss|less|sass)$"
+need_checks=$(echo "$staged" | grep -E $ext_list || echo "")
+if [[ -z $need_checks ]]; then
+    # Check format (skipped)
+	echo "> Check format on staged files..."
+    echo "$passed No file to check. (skipped)"
+	echo
+
+	# Check lint (skipped)
+	echo "> Check lint on staged files..."
+    echo "$passed No file to check. (skipped)"
+    exit 0
+fi
 
 # Check format
 echo "> Check format on staged files..."
